dist: trusty
language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - "sudo apt-get -qq update"
  - "sudo apt-get install -y clamav-daemon" 
  - "python setup.py -q install"
  - "pip install pytest-pep8"
# command to run tests
script: pytest

